<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin 1.0
// Source: message.proto
//   Date: 2016-10-29 20:28:55

namespace sample {

  class HelloRequest extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $text = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'sample.HelloRequest');

      // REQUIRED STRING text = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "text";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <text> has a value
     *
     * @return boolean
     */
    public function hasText(){
      return $this->_has(1);
    }
    
    /**
     * Clear <text> value
     *
     * @return \sample\HelloRequest
     */
    public function clearText(){
      return $this->_clear(1);
    }
    
    /**
     * Get <text> value
     *
     * @return string
     */
    public function getText(){
      return $this->_get(1);
    }
    
    /**
     * Set <text> value
     *
     * @param string $value
     * @return \sample\HelloRequest
     */
    public function setText( $value){
      return $this->_set(1, $value);
    }
  }
}

namespace sample {

  class HelloReply extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $text = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'sample.HelloReply');

      // REQUIRED STRING text = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "text";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <text> has a value
     *
     * @return boolean
     */
    public function hasText(){
      return $this->_has(1);
    }
    
    /**
     * Clear <text> value
     *
     * @return \sample\HelloReply
     */
    public function clearText(){
      return $this->_clear(1);
    }
    
    /**
     * Get <text> value
     *
     * @return string
     */
    public function getText(){
      return $this->_get(1);
    }
    
    /**
     * Set <text> value
     *
     * @param string $value
     * @return \sample\HelloReply
     */
    public function setText( $value){
      return $this->_set(1, $value);
    }
  }
}

namespace sample {

  class GreeterClient extends \Grpc\BaseStub {

    public function __construct($hostname, $opts, $channel = null) {
      parent::__construct($hostname, $opts, $channel);
    }
    /**
     * @param sample\HelloRequest $input
     */
    public function SayHello(\sample\HelloRequest $argument, $metadata = array(), $options = array()) {
      return $this->_simpleRequest('/sample.Greeter/SayHello', $argument, '\sample\HelloReply::deserialize', $metadata, $options);
    }
  }
}
